version: "3.3"

services:
  calibration:
    image: prismadriver:0.1.0
    restart: always
    command: python3 /astrometry/workspace/calibrate.py
    volumes:
      - /prismadata/stations:/astrometry/workspace/captures
      - /prismadata/detections/multiple:/astrometry/workspace/events
      - /prismadata/runtime:/astrometry/workspace/runtime
      - /prismadata/settings:/astrometry/workspace/settings
      - /prismadata/astrometry:/astrometry/workspace/astrometry
      - /prismadata/results:/astrometry/workspace/results
