version: "3.3"

services:
  rsync_captures:
    image: instrumentisto/rsync-ssh
    restart: always
    volumes:
      - ${HOME}/.ssh:/root/.ssh
      - /prismadata:/prismadata
    command: rsync -e "ssh -i /root/.ssh/id_rsa" --progress -r controls@prisma.ia2.inaf.it:/mnt/rsync_captures/ /prismadata/rsync_captures/
  rsync_events:
      image: instrumentisto/rsync-ssh
      restart: always
      volumes:
        - ${HOME}/.ssh:/root/.ssh
        - /prismadata:/prismadata
      command:  rsync -e "ssh -i /root/.ssh/id_rsa" --progress -r controls@prisma.ia2.inaf.it:/mnt/rsync_events/ /prismadata/rsync_events/
  sync_fripon:
    image: sync_fripon:0.1.0
    restart: always
    # data will be downloaded in the following 2 directories:
    # /prismadata/stations -- detections
    # /prismadata/detections/multiple -- events
    volumes:
        - ${HOME}/.ssh:/root/.ssh
        - /prismadata:/prismadata
