version: "3.3"

services:
  db:
    image: prismadb:0.1.0
    restart: always
    ports: 
        - "3306:3306"
    volumes:
      - /prisma_volumes/mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=prisma
      - MYSQL_PASSWORD=prismasecret
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=inaf_prisma
  web:
    image: webserver:0.1.0
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
  driver:
    image: prismadriver:0.1.0
    restart: always
    volumes:
        - /prismadata:/env/INAF_PRISMA/raspberry
        - /prismadata/stations:/env/INAF_PRISMA/PRISMA/workspace/events
    depends_on:
        - db
  sync_fripon:
    image: sync_fripon:0.1.0
    restart: always
    command: ["python3", "-u", "/sync_fripon.py"]  
    # data will be downloaded in the following 2 directories:
    # /prismadata/stations -- detections
    # /prismadata/detections/multiple -- events
    volumes:
        - ${HOME}/.ssh:/root/.ssh
        - /prismadata:/prismadata
