version: "3.3"

services:
  db:
    image: prismadb:0.1.0
    restart: always
    ports: 
        - "3306:3306"
    volumes:
      - /prisma_volumes/mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=prisma
      - MYSQL_PASSWORD=prismasecret
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=inaf_prisma
  web:
    image: webserver:0.1.0
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
  idl:
    image: idl:0.1.0
    restart: always
    volumes:
      - /prismadata/stations:/astrometry/workspace/captures
      - /prismadata/detections/multiple:/astrometry/workspace/events
      - /prismadata/runtime:/astrometry/workspace/runtime
      - /prismadata/settings:/astrometry/workspace/settings
      - /prismadata/astrometry:/astrometry/workspace/astrometry
      - /prismadata/results:/astrometry/workspace/results
  rsync_captures:
    image: instrumentisto/rsync-ssh
    restart: always
    volumes:
      - ${HOME}/.ssh:/root/.ssh
      - /prismadata:/prismadata
    command: rsync -e "ssh -i /root/.ssh/id_rsa" --progress -r controls@prisma.ia2.inaf.it:/mnt/rsync_captures/ /prismadata/rsync_captures/
  rsync_events:
      image: instrumentisto/rsync-ssh
      restart: always
      volumes:
        - ${HOME}/.ssh:/root/.ssh
        - /prismadata:/prismadata
      command:  rsync -e "ssh -i /root/.ssh/id_rsa" --progress -r controls@prisma.ia2.inaf.it:/mnt/rsync_events/ /prismadata/rsync_events/
  sync_fripon:
    image: sync_fripon:0.1.0
    restart: always
    command: ["python3", "-u", "/sync_fripon.py", "-d", "30"]  
    # data will be downloaded in the following 2 directories:
    # /prismadata/stations -- detections
    # /prismadata/detections/multiple -- events
    volumes:
        - ${HOME}/.ssh:/root/.ssh
        - /prismadata:/prismadata
