FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y python3.8 python3-pip python3.8-dev 

COPY idl/astrometry_v1.30/workspace/settings/solutions.ini /solutions.ini
COPY requirements.txt /requirements.txt 

RUN python3 -m pip install setuptools
RUN python3 -m pip install -r /requirements.txt 

COPY src /prisma_repo

CMD ["python3","-u", "/prisma_repo/run_sync_fripon.py"]


