FROM python:3.8-slim

RUN pip install paramiko

COPY ssh_client.py /ssh_client.py
COPY sync_fripon.py /sync_fripon.py

RUN apt-get update && \
    apt-get install -y cron

RUN touch /var/log/cron.log

RUN (crontab -u root -l; echo "* * * * * echo hello >> /var/log/cron.log") | crontab -u root -

CMD cron && tail -f /var/log/cron.log

